### ISSUE TITLE
Wrong backgroup color for the menu on top right

### ISSUE THREAD

**Issue by alexandrenavarro** [SimpleMobileTools/Simple-Thank-You#66] opened 2021-01-18 21:00 UTC
Wrong backgroup color for the menu on top right.

When I activate the theme (Black and White), everything is ok except the background on the menu on the top right where you have generally Parameters / About notably. The background is dark grey not black.

The problem occurs on all the apps (on pro one, it is dark gray, on some not pro app it was white).

Thank you for the amazing work you made, I just discovered because they are available in f-droid  and I want to have open source apps for some critical apps and you made a fantastic job (I bought all).

**Comment by tibbi** [comment] 2021-01-19 13:41
Sadly that color is difficult to customize, so currently it is dark grey no matter what theme or colors you set. Anyway, as it affects all apps, it is already reported elsewhere. Duplicate of https://github.com/SimpleMobileTools/General-Discussion/issues/108 . Thanks

**Closed by tibbi** 2021-01-19 13:41 UTC

**Comment by alexandrenavarro** [comment] 2021-01-19 20:08
Ok, thanks for the answer, I didn't realize the problem is not only on simple tools but on all the applications I used but as I used real Black White theme on simple tool (compared to some other app where it is only a Dark grey White), I think I noticed it.
